// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/waza/internal/execution (interfaces: CopilotSession,CopilotClient)
//
// Generated by this command:
//
//	mockgen -package main -destination copilot_client_wrapper_mocks_test.go github.com/microsoft/waza/internal/execution CopilotSession,CopilotClient
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	copilot "github.com/github/copilot-sdk/go"
	execution "github.com/microsoft/waza/internal/execution"
	gomock "go.uber.org/mock/gomock"
)

// MockCopilotSession is a mock of CopilotSession interface.
type MockCopilotSession struct {
	ctrl     *gomock.Controller
	recorder *MockCopilotSessionMockRecorder
	isgomock struct{}
}

// MockCopilotSessionMockRecorder is the mock recorder for MockCopilotSession.
type MockCopilotSessionMockRecorder struct {
	mock *MockCopilotSession
}

// NewMockCopilotSession creates a new mock instance.
func NewMockCopilotSession(ctrl *gomock.Controller) *MockCopilotSession {
	mock := &MockCopilotSession{ctrl: ctrl}
	mock.recorder = &MockCopilotSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopilotSession) EXPECT() *MockCopilotSessionMockRecorder {
	return m.recorder
}

// Disconnect mocks base method.
func (m *MockCopilotSession) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockCopilotSessionMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockCopilotSession)(nil).Disconnect))
}

// On mocks base method.
func (m *MockCopilotSession) On(handler copilot.SessionEventHandler) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "On", handler)
	ret0, _ := ret[0].(func())
	return ret0
}

// On indicates an expected call of On.
func (mr *MockCopilotSessionMockRecorder) On(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "On", reflect.TypeOf((*MockCopilotSession)(nil).On), handler)
}

// SendAndWait mocks base method.
func (m *MockCopilotSession) SendAndWait(ctx context.Context, options copilot.MessageOptions) (*copilot.SessionEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndWait", ctx, options)
	ret0, _ := ret[0].(*copilot.SessionEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAndWait indicates an expected call of SendAndWait.
func (mr *MockCopilotSessionMockRecorder) SendAndWait(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndWait", reflect.TypeOf((*MockCopilotSession)(nil).SendAndWait), ctx, options)
}

// SessionID mocks base method.
func (m *MockCopilotSession) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockCopilotSessionMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockCopilotSession)(nil).SessionID))
}

// MockCopilotClient is a mock of CopilotClient interface.
type MockCopilotClient struct {
	ctrl     *gomock.Controller
	recorder *MockCopilotClientMockRecorder
	isgomock struct{}
}

// MockCopilotClientMockRecorder is the mock recorder for MockCopilotClient.
type MockCopilotClientMockRecorder struct {
	mock *MockCopilotClient
}

// NewMockCopilotClient creates a new mock instance.
func NewMockCopilotClient(ctrl *gomock.Controller) *MockCopilotClient {
	mock := &MockCopilotClient{ctrl: ctrl}
	mock.recorder = &MockCopilotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopilotClient) EXPECT() *MockCopilotClientMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockCopilotClient) CreateSession(ctx context.Context, config *copilot.SessionConfig) (execution.CopilotSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, config)
	ret0, _ := ret[0].(execution.CopilotSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockCopilotClientMockRecorder) CreateSession(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockCopilotClient)(nil).CreateSession), ctx, config)
}

// DeleteSession mocks base method.
func (m *MockCopilotClient) DeleteSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockCopilotClientMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockCopilotClient)(nil).DeleteSession), ctx, sessionID)
}

// ResumeSessionWithOptions mocks base method.
func (m *MockCopilotClient) ResumeSessionWithOptions(ctx context.Context, sessionID string, config *copilot.ResumeSessionConfig) (execution.CopilotSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSessionWithOptions", ctx, sessionID, config)
	ret0, _ := ret[0].(execution.CopilotSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeSessionWithOptions indicates an expected call of ResumeSessionWithOptions.
func (mr *MockCopilotClientMockRecorder) ResumeSessionWithOptions(ctx, sessionID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSessionWithOptions", reflect.TypeOf((*MockCopilotClient)(nil).ResumeSessionWithOptions), ctx, sessionID, config)
}

// Start mocks base method.
func (m *MockCopilotClient) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCopilotClientMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCopilotClient)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockCopilotClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockCopilotClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCopilotClient)(nil).Stop))
}
